version: 2
updates:
  # Fetch and update latest `yarn` packages
  - package-ecosystem: yarn
    directory: '/'
    schedule:
      interval: daily
      time: '00:00'
    open-pull-requests-limit: 10
    reviewers:
      - samuk-a
    assignees:
      - samuk-a
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
