version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build:
    executor:
      name: node/default
      tag: '18.14'
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Update yarn
          command: sudo npm install -g yarn@latest --force
      - node/install-packages:
          pkg-manager: yarn
          override-ci-command: yarn install --no-progress --non-interactive --silent --pure-lockfile
      - run:
          name: Build output
          command: yarn generate
      - run:
          name: Deploy static files
          command: |
            sudo apt update
            sudo apt -qq install git-ftp
            git init
            git config user.name "${gitUser}"
            git config user.email "${gitEmail}"
            git add .output/public
            git commit -m "Deploying public folder"
            git ftp push --force --syncroot .output/public/ --user "${username}" --passwd "${password}" ${ftp_location}

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
          context: Hostinger Deploy
