version: 2

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run linter
          command: yarn lint

      - run:
          name: Build project
          command: yarn generate:gh-pages

      - run:
          name: Install and configure ghpages dependencies
          command: |
            yarn add gh-pages -D
            git config user.email "samuel.santiago@ufu.br"
            git config user.name "samuk-a"
      - add_ssh_keys:
          fingerprints:
            - '6f:2c:fe:95:bf:22:21:98:fd:eb:70:c5:ec:a3:a3:5b'

      - run:
          name: Deploy to GitHub Pages
          command: './node_modules/.bin/gh-pages --dotfiles --message "[skip ci] Updates" -d dist'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
