version: 2.1
orbs:
  node: circleci/node@5.1.0
  heroku: circleci/heroku@2.0.0
jobs:
  test:
    executor:
      name: node/default
      tag: '18.14'
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Update yarn
          command: sudo npm install -g yarn@latest
      - node/install-packages:
          pkg-manager: yarn
          cache-path: ~/project/node_modules
          override-ci-command: yarn install --no-progress --non-interactive --silent --pure-lockfile
      - run:
          name: Run test suite
          command: yarn test_ci
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    docker:
      - image: circleci/node:18.14.1
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
